### ISSUE TITLE
Even after deleting Toolbox, apphide.css tries to load

### ISSUE THREAD

**Issue by interkelstar** [WisdomSky/CasaOS-Toolbox#1]
Basically what title says, I've installes Toolbox, then deleted but apphide.css still tries to load and moreover it has ip, not domain so i cannot load it when accessing CasaOS outside

**Comment by WisdomSky** [comment]
hi @interkelstar, in the settings, you can  change the host into a domain and then restart the toolbox app.

**Comment by interkelstar** [comment]
I have deleted toolbox already. But the problem is that apphide.css resource is not deleted

**Comment by WisdomSky** [comment]
Hi, when deleting the container, it will not remove the apphide.css that was injected into casaos' index file, but it should not affect how the casaos behaves even if the file does not exist anymore.

**Comment by emtalk-qf** [comment]
I'm having the same problem!

After uninstalling Toolbox, the page source code still retains the 
`<link rel="stylesheet" type="text/css" href="http://192.168.3.140:8088/casaos-toolbox/apphide.css">`

**Comment by WisdomSky** [comment]
@emtalk-qf please read the comment above.

I'm now closing this issue.

**Comment by interkelstar** [comment]
> it should not affect how the casaos behaves even if the file does not exist anymore

It is not true. My experience showed that after deleting Toolbox, if you access CasaOS from the web it takes sometimes significantly longer, showing nothing but the white page. After investigation of this issue I found in the network requests that all this time it was trying to load apphide.css and only when failed with ERR_TIMEOUT it continued to load the CasaOS homepage. So the consequences are significant for CasaOS UX, not to mention that without letting users know of any not cleaned trash it can be considered as a bloatware for CasaOS.

**Comment by WisdomSky** [comment]
A new version (v0.2) has been released which contains a new option in the settings to clean up the injected files.

![image](https://github.com/WisdomSky/CasaOS-Toolbox/assets/6792172/a0502062-b7f5-4bb5-93cf-9478387f12e5)
