### ISSUE TITLE
Issue #1 still needs to be fixed

### ISSUE THREAD

**Issue by interkelstar** [WisdomSky/CasaOS-Toolbox#2]
> it should not affect how the casaos behaves even if the file does not exist anymore

It is not true. My experience showed that after deleting Toolbox, if you access CasaOS from the web it takes sometimes significantly longer, showing nothing but the white page. After investigation of this issue I found in the network requests that all this time it was trying to load apphide.css and only when failed with ERR_TIMEOUT it continued to load the CasaOS homepage. So the consequences are significant for CasaOS UX, not to mention that without letting users know of any not cleaned trash it can be considered as a bloatware for CasaOS.

_Originally posted by @interkelstar in https://github.com/WisdomSky/CasaOS-Toolbox/issues/1#issuecomment-1723334667_

**Comment by WisdomSky** [comment]
Hi, I've already heard your concern. Please stop spamming the issues page by creating a new issue rather than re-opening the previous issue. 

I will add an option to clean the injected code in the next release. 

Closing as duplicate.
