### ISSUE TITLE
The app makes requests via HTTP when CasaOS & Toolbox are behind reverse-proxy

### ISSUE THREAD

**Issue by MELVARDEV** [WisdomSky/CasaOS-Toolbox#3]
When CasaOS is open via the URL of the reverse proxy, i.e "https://casaos.example.com", it tries to fetch the apphide.css from "http://[public-ip]:8088/casaos-toolbox/apphide.css'".
Also, when the app page itself is behind a reverse-proxy, it tries to load the JS over http, "http://toolbox.casaos.example.com/build/assets/app-786e5331.js"

**Comment by WisdomSky** [comment]
Hi @MELVARDEV,

you can change the host in the settings.

after changing the host, click save and restart the toolbox app.

i.e:

192.168.1.123 -> casaos.example.com

**Comment by MELVARDEV** [comment]
Hi again and thank you for your time, I tried to troubleshoot it, but I can't quite figure it out. It appears that the change host option doesn't do anything for some reason, it just goes back to the default value after refresh and / or restart of either the app or the whole system. 

I've looked at the logs of the app and via "docker logs casaos-toolbox-app-1" and I can't see any new log entries when changing the host option. Is there perhaps a config file where the host config option is stored?

**Comment by WisdomSky** [comment]
> Hi again and thank you for your time, I tried to troubleshoot it, but I can't quite figure it out. It appears that the change host option doesn't do anything for some reason, it just goes back to the default value after refresh and / or restart of either the app or the whole system.

Hi, just save it and disregard that the display doesn't update. It's a bug and I've fixed it but hasn't released the patch yet.

Just save and then restart the app.

**Comment by WisdomSky** [comment]
For example:

![image](https://github.com/WisdomSky/CasaOS-Toolbox/assets/6792172/c0d4f8c4-0d09-4d6c-a5f7-7c3535143743)

**Comment by WisdomSky** [comment]
and then restart the app by clicking the refresh button on the app dropdown in casaos:

![image](https://github.com/WisdomSky/CasaOS-Toolbox/assets/6792172/75dc7c2b-5c3f-483f-aa75-17638a5823b2)

**Comment by MELVARDEV** [comment]
Alright, thank you for the update on this! I'm going to fiddle around tomorrow and let you know how it goes, perhaps if something would still be wrong then I'll wait for the new update release, no rush here :P

**Comment by WisdomSky** [comment]
Hi @MELVARDEV,

A new update has been released v0.2, it included the fix for this issue where the host does not reflect after saving.

![image](https://github.com/WisdomSky/CasaOS-Toolbox/assets/6792172/60fddf11-0b06-4739-80d3-f48cf6c2df9b)

and set the `FORCE_HTTPS` environment_variable into `true` in the app docker-compose settings in CasaOS.

Let me know if the new update solved your issue. thanks

**Comment by MELVARDEV** [comment]
Hi, great update, I've tested it briefly and almost everything works perfectly, the apps are hidden correctly.
The `host` option still shows up as the default, though, functionally everything works as intended behind the reverse proxy after setting the `FORCE_HTTPS` variable. Appreciate the fast update!
