### ISSUE TITLE
Add authentication to the toolbox panel

### ISSUE THREAD

**Issue by MELVARDEV** [WisdomSky/CasaOS-Toolbox#4]
It would be very handy to have some kind of authentication to access the panel, especially if it has to be accessed over the internet. Even an environment variable password would be sufficient for now.

**Comment by WisdomSky** [comment]
Hi @MELVARDEV,

Thanks for the suggestion. I'll add this on the next release. most probably next week.

**Comment by WisdomSky** [comment]
Hi @MELVARDEV,

A new update has been released v0.2, which included an authentication feature.
